# Generated by Django 3.2 on 2021-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avtar',
            field=models.ImageField(default='avtar/avtar.jpg', upload_to='avtar/'),
        ),
    ]
