# Generated by Django 3.2.6 on 2021-08-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avtar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
