# Generated by Django 3.2.6 on 2021-08-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_is_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_block',
        ),
    ]
