# Generated by Django 3.2.6 on 2021-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_is_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('received', 'received'), ('block', 'block')], max_length=10),
        ),
    ]
