# Generated by Django 3.2.6 on 2021-08-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='updated',
        ),
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
